apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort # Use LoadBalancer for cloud-based clusters
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000 # NodePort range is 30000-32767
