### GET /
GET http://localhost:5000

### POST /
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username":"mabs@gmail.com",
  "password":"123123123"
}


### POST /
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username":"mabs@gmail.com",
  "password":"123123123"
}


###TODO testing
### GET todos
POST http://localhost:5000/api/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczNTIwNzQwMCwiZXhwIjoxNzM1MjExMDAwfQ.LOyzGI9aTC-NJkc5JNEPjPK8TJBrjXoUTgjoReU1nQU

{
  "title": "New Todo",
  "description": "Description for the new todo"
}

